<?php

namespace AppBundle\Repository;

/**
 * GoShortcutUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoShortcutUserRepository extends \Doctrine\ORM\EntityRepository
{
}
