<?php

namespace AppBundle\Repository;

/**
 * GoShortcutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoShortcutRepository extends \Doctrine\ORM\EntityRepository
{
}
